server:
  port: 8500

spring:
  cloud:
    config:
      server:
        git:
          default-label: @active.profile@
          uri: https://github.com/sbxiaobao/config-repo.git
          clone-on-start: false
          username:
          password:
        native:
          search-locations: classpath:repo/@active.profile@
  application:
    name: @project.name@

eureka:
  instance:
    prefer-ip-address: false
    status-page-url-path: /management/info
    health-check-url-path: /management/health
  client:
    register-with-eureka: false
    fetch-registry: false