eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8500}/eureka/
  instance:
    prefer-ip-address: false
management:
  security:
    enabled: false

spring:
  application:
    name: user-service
  profiles:
    active: dev

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutorETRIES: 0
  httpclient:
    enabled: false
  okhttp:
    enabled: true

server:
  port: 8082
